import cv2
import matplotlib.pyplot as plt
img=cv2.imread ('Grayscale.tif')
# cv2. imshow ('Input Image', img)
sobel_x = cv2. Sobel (img, -1, 1, 0, 3)
# cv2. imshow("Sobel X", sobel_x)
sobel_y = cv2.Sobel (img,-1, 0, 1, 3)
# cv2.imshow('Sobel Y', sobel_y)
combine = cv2.addWeighted(sobel_x, 1, sobel_y, 1.5, 1)
# cv2.imshow ("Combine X and Y", combine)
ret, thrs= cv2.threshold (combine, 100, 255, type=cv2.THRESH_BINARY)
cv2.imshow('After Threshold', thrs)
# cv2.waitKey(0)
# cv2. destroyAllWindows()
plt.subplot(231),plt.imshow(img),plt.title("GrayScale Image"),plt.axis('off')
plt.subplot(232),plt.imshow(sobel_x),plt.title("Sobel X"),plt.axis('off')
plt.subplot(233),plt.imshow(sobel_y),plt.title("Sobel Y"),plt.axis('off')
plt.subplot(234),plt.imshow(combine),plt.title("Combine X and y"),plt.axis('off')
plt.subplot(235),plt.imshow(thrs),plt.title("Threshold"),plt.axis('off')
plt.tight_layout()